[project]
name = "Data-Equity"
version = "0.1.0"
description = "Project 3 Data Equity"
dependencies = [
    "pandas>=2.3.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
